# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dcc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dcc.proto',
  package='tutorial',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\tdcc.proto\x12\x08tutorial\"\xfd\x03\n\x03\x44\x43\x43\x12\x0f\n\x07version\x18\x01 \x02(\r\x12\x11\n\talgorithm\x18\x02 \x02(\r\x12\x0b\n\x03kid\x18\x03 \x02(\r\x12\x12\n\nnot_before\x18\x04 \x02(\r\x12\x11\n\tnot_after\x18\x05 \x02(\r\x12\x0c\n\x04name\x18\x06 \x02(\t\x12\x0f\n\x07surname\x18\x07 \x02(\t\x12\x15\n\rdate_of_birth\x18\x08 \x02(\r\x12\x0f\n\x07\x64isease\x18\n \x02(\r\x12\"\n\x01v\x18\x0b \x01(\x0b\x32\x15.tutorial.DCC.VaccineH\x00\x12\x1f\n\x01t\x18\x0c \x01(\x0b\x32\x12.tutorial.DCC.TestH\x00\x12#\n\x01r\x18\r \x01(\x0b\x32\x16.tutorial.DCC.RecoveryH\x00\x1a\\\n\x07Vaccine\x12\x0f\n\x07vaccine\x18\x01 \x02(\r\x12\x12\n\ndoses_done\x18\x02 \x02(\r\x12\x16\n\x0e\x64oses_required\x18\x03 \x02(\r\x12\x14\n\x0c\x64\x61te_vaccine\x18\x04 \x02(\r\x1a\x41\n\x04Test\x12\x13\n\x0btest_result\x18\x01 \x02(\x08\x12\x11\n\ttest_used\x18\x02 \x02(\r\x12\x11\n\tdate_test\x18\x03 \x02(\r\x1a\x44\n\x08Recovery\x12\x11\n\tdate_test\x18\x01 \x02(\r\x12\x11\n\tdate_from\x18\x02 \x02(\r\x12\x12\n\ndate_until\x18\x03 \x02(\rB\x06\n\x04type')
)




_DCC_VACCINE = _descriptor.Descriptor(
  name='Vaccine',
  full_name='tutorial.DCC.Vaccine',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vaccine', full_name='tutorial.DCC.Vaccine.vaccine', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='doses_done', full_name='tutorial.DCC.Vaccine.doses_done', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='doses_required', full_name='tutorial.DCC.Vaccine.doses_required', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date_vaccine', full_name='tutorial.DCC.Vaccine.date_vaccine', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=296,
  serialized_end=388,
)

_DCC_TEST = _descriptor.Descriptor(
  name='Test',
  full_name='tutorial.DCC.Test',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='test_result', full_name='tutorial.DCC.Test.test_result', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='test_used', full_name='tutorial.DCC.Test.test_used', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date_test', full_name='tutorial.DCC.Test.date_test', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=390,
  serialized_end=455,
)

_DCC_RECOVERY = _descriptor.Descriptor(
  name='Recovery',
  full_name='tutorial.DCC.Recovery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='date_test', full_name='tutorial.DCC.Recovery.date_test', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date_from', full_name='tutorial.DCC.Recovery.date_from', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date_until', full_name='tutorial.DCC.Recovery.date_until', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=457,
  serialized_end=525,
)

_DCC = _descriptor.Descriptor(
  name='DCC',
  full_name='tutorial.DCC',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='tutorial.DCC.version', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='algorithm', full_name='tutorial.DCC.algorithm', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kid', full_name='tutorial.DCC.kid', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='not_before', full_name='tutorial.DCC.not_before', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='not_after', full_name='tutorial.DCC.not_after', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='tutorial.DCC.name', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='surname', full_name='tutorial.DCC.surname', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date_of_birth', full_name='tutorial.DCC.date_of_birth', index=7,
      number=8, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disease', full_name='tutorial.DCC.disease', index=8,
      number=10, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v', full_name='tutorial.DCC.v', index=9,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='t', full_name='tutorial.DCC.t', index=10,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='r', full_name='tutorial.DCC.r', index=11,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DCC_VACCINE, _DCC_TEST, _DCC_RECOVERY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='type', full_name='tutorial.DCC.type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=24,
  serialized_end=533,
)

_DCC_VACCINE.containing_type = _DCC
_DCC_TEST.containing_type = _DCC
_DCC_RECOVERY.containing_type = _DCC
_DCC.fields_by_name['v'].message_type = _DCC_VACCINE
_DCC.fields_by_name['t'].message_type = _DCC_TEST
_DCC.fields_by_name['r'].message_type = _DCC_RECOVERY
_DCC.oneofs_by_name['type'].fields.append(
  _DCC.fields_by_name['v'])
_DCC.fields_by_name['v'].containing_oneof = _DCC.oneofs_by_name['type']
_DCC.oneofs_by_name['type'].fields.append(
  _DCC.fields_by_name['t'])
_DCC.fields_by_name['t'].containing_oneof = _DCC.oneofs_by_name['type']
_DCC.oneofs_by_name['type'].fields.append(
  _DCC.fields_by_name['r'])
_DCC.fields_by_name['r'].containing_oneof = _DCC.oneofs_by_name['type']
DESCRIPTOR.message_types_by_name['DCC'] = _DCC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DCC = _reflection.GeneratedProtocolMessageType('DCC', (_message.Message,), dict(

  Vaccine = _reflection.GeneratedProtocolMessageType('Vaccine', (_message.Message,), dict(
    DESCRIPTOR = _DCC_VACCINE,
    __module__ = 'dcc_pb2'
    # @@protoc_insertion_point(class_scope:tutorial.DCC.Vaccine)
    ))
  ,

  Test = _reflection.GeneratedProtocolMessageType('Test', (_message.Message,), dict(
    DESCRIPTOR = _DCC_TEST,
    __module__ = 'dcc_pb2'
    # @@protoc_insertion_point(class_scope:tutorial.DCC.Test)
    ))
  ,

  Recovery = _reflection.GeneratedProtocolMessageType('Recovery', (_message.Message,), dict(
    DESCRIPTOR = _DCC_RECOVERY,
    __module__ = 'dcc_pb2'
    # @@protoc_insertion_point(class_scope:tutorial.DCC.Recovery)
    ))
  ,
  DESCRIPTOR = _DCC,
  __module__ = 'dcc_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.DCC)
  ))
_sym_db.RegisterMessage(DCC)
_sym_db.RegisterMessage(DCC.Vaccine)
_sym_db.RegisterMessage(DCC.Test)
_sym_db.RegisterMessage(DCC.Recovery)


# @@protoc_insertion_point(module_scope)
