"""empty message

Revision ID: dce6060829ab
Revises: 
Create Date: 2021-08-30 20:35:41.028292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dce6060829ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('fl_date', sa.Date(), nullable=True),
    sa.Column('op_carrier_airline_id', sa.Integer(), nullable=True),
    sa.Column('op_carrier_fl_num', sa.String(length=10), nullable=True),
    sa.Column('origin_airport_id', sa.Integer(), nullable=True),
    sa.Column('origin', sa.String(length=3), nullable=True),
    sa.Column('origin_city_name', sa.String(length=100), nullable=True),
    sa.Column('origin_state_nm', sa.String(length=100), nullable=True),
    sa.Column('dest_airport_id', sa.Integer(), nullable=True),
    sa.Column('dest', sa.Integer(), nullable=True),
    sa.Column('dest_city_name', sa.String(length=100), nullable=True),
    sa.Column('dest_state_nm', sa.String(length=100), nullable=True),
    sa.Column('dep_time', sa.Integer(), nullable=True),
    sa.Column('dep_delay', sa.Float(), nullable=True),
    sa.Column('arr_time', sa.Integer(), nullable=True),
    sa.Column('arr_delay', sa.Float(), nullable=True),
    sa.Column('cancelled', sa.Boolean(), nullable=True),
    sa.Column('air_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flights')
    # ### end Alembic commands ###
